//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionSetEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionSetEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1025:&quot;Arabic&quot;,
        ///1069:&quot;Basque (Basque)&quot;,
        ///1026:&quot;Bulgarian (Bulgaria)&quot;,
        ///1027:&quot;Catalan (Catalan)&quot;,
        ///3076:&quot;Chinese (Hong Kong S.A.R.)&quot;,
        ///2052:&quot;Chinese (PRC)&quot;,
        ///1028:&quot;Chinese (Taiwan)&quot;,
        ///1050:&quot;Croatian (Croatia)&quot;,
        ///1029:&quot;Czech&quot;,
        ///1030:&quot;Danish&quot;,
        ///1043:&quot;Dutch&quot;,
        ///1033:&quot;English&quot;,
        ///1061:&quot;Estonian (Estonia)&quot;,
        ///1035:&quot;Finnish&quot;,
        ///1036:&quot;French&quot;,
        ///1110:&quot;Galician (Galician)&quot;,
        ///1031:&quot;German&quot;,
        ///1032:&quot;Greek&quot;,
        ///1037:&quot;Hebrew&quot;,
        ///1081:&quot;Hindi (India)&quot;,
        ///1038:&quot;Hungarian&quot;,
        ///1057:&quot;Indonesian&quot;,
        ///1040:&quot;Italian&quot;,
        ///1041:&quot;Japanese&quot;,
        ///108 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
    }
}
